// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function IsProxyRunning():Promise<boolean>;

export function SetAutoStart(arg1:boolean):Promise<string>;

export function StartProxy(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StopProxy():Promise<void>;
